# Generated by Django 5.0.6 on 2024-06-21 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orden_de_retiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField()),
                ('retirado', models.BooleanField(default=False)),
                ('epp', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app1.epp')),
                ('obrero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.obreros')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.supervisor')),
            ],
            options={
                'verbose_name': 'Orden de retiro',
                'verbose_name_plural': 'Ordenes de Retiro',
                'db_table': 'Orden de retiro',
            },
        ),
    ]
