# Generated by Django 5.0.6 on 2024-06-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, verbose_name='Título')),
                ('Descripción', models.CharField(max_length=30, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'tipo_supervisor',
                'verbose_name_plural': 'Tipos de Supervisores',
                'db_table': 'tipo_supervisor',
            },
        ),
    ]
