# Generated by Django 5.0.6 on 2024-06-13 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_tipo_supervisor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo_supervisor',
            options={'verbose_name': 'Tipo supervisor', 'verbose_name_plural': 'Tipos de Supervisores'},
        ),
        migrations.RenameField(
            model_name='tipo_supervisor',
            old_name='Descripción',
            new_name='descripción',
        ),
    ]
