# Generated by Django 5.0.6 on 2024-06-14 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_tipo_supervisor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo_supervisor',
            options={'verbose_name': 'Tipo de Supervisor', 'verbose_name_plural': 'Tipos de Supervisores'},
        ),
        migrations.AddField(
            model_name='supervisor',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.tipo_supervisor'),
        ),
    ]
