# Generated by Django 5.0.6 on 2024-06-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_tipo_supervisor_options_supervisor_cargo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='obrero',
            new_name='obreros',
        ),
        migrations.AlterModelOptions(
            name='material_de_epp',
            options={'verbose_name': 'Material', 'verbose_name_plural': 'Materiales'},
        ),
        migrations.AlterField(
            model_name='material_de_epp',
            name='nombre_material',
            field=models.CharField(max_length=50, verbose_name='Nombre Material'),
        ),
    ]
