# Generated by Django 5.0.6 on 2024-06-20 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_epp_nombre_epp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orden_de_retiro',
            options={'verbose_name': 'Orden de retiro', 'verbose_name_plural': 'Ordenes de Retiro'},
        ),
        migrations.AddField(
            model_name='epp',
            name='marca',
            field=models.CharField(max_length=40, null=True, verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='epp',
            name='nombre_epp',
            field=models.CharField(default='epp', max_length=40, verbose_name='nombre_EPP'),
        ),
        migrations.AlterField(
            model_name='orden_de_retiro',
            name='epp',
            field=models.ForeignKey(blank=True, default='epp', on_delete=django.db.models.deletion.CASCADE, to='app1.epp'),
        ),
        migrations.AlterModelTable(
            name='orden_de_retiro',
            table='Orden de retiro',
        ),
    ]
