# Generated by Django 5.0.6 on 2024-06-20 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_orden_de_retiro_epp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden_de_retiro',
            name='epp',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app1.epp'),
        ),
    ]
