# Generated by Django 5.0.6 on 2024-06-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_orden_de_retiro_epp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epp',
            name='nombre_epp',
            field=models.CharField(default='sin nombre', max_length=40, verbose_name='nombre_EPP'),
        ),
    ]
