# Generated by Django 5.0.6 on 2024-06-20 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_epp_nombre_epp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='epp',
            options={'verbose_name': 'Elemento de Protección Personal', 'verbose_name_plural': 'Elementos de Protección Personal'},
        ),
        migrations.AlterField(
            model_name='epp',
            name='marca',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='epp',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.material_de_epp', verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='epp',
            name='nombre_epp',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Nombre del EPP'),
        ),
        migrations.AlterField(
            model_name='epp',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
    ]
