# Generated by Django 5.0.6 on 2024-06-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_epp_options_alter_epp_marca_alter_epp_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epp',
            name='nombre_epp',
            field=models.CharField(blank=True, default=0, max_length=40, verbose_name='Nombre del EPP'),
        ),
    ]
