# Generated by Django 5.0.6 on 2024-06-20 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_epp_nombre_epp'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='epp',
            table='epp',
        ),
    ]
